name: cache

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Copy repo
        uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-cache-file-
            ${{ runner.os }}-
      - name: Show cache file
        run: echo '${{toJson(steps.cache-step.outputs)}}'
      - name: Install node_modules
        run: npm install
      