name: Env workflow

on: [push]
env:
  WF_CASTOM_ENV: 1
jobs:
  run-first-command: 
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: show env
        run: | 
          echo $WF_CASTOM_ENV
          echo '${{vars.STATUS}}'
          echo '${{secrets.PASSWORD}}'
          